#spring.application.name=api-gateway
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#eureka.client.fetch-registry=true
#eureka.client.register-with-eureka=true
#server.port=8080
#
#eureka.instance.prefer-ip-address=true
#eureka.instance.lease-expiration-duration-in-seconds=10
#eureka.instance.lease-renewal-interval-in-seconds=10
#
#jwt.secretKey=AOIGPIAHRPOJfw0r9twrmjgpoqrj0t9hq2530gwmrojgpisefhogihsne0ty25ut0whtpghpeg